[v1]
"cargo-aws-lambda 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-aws-lambda"]
"cargo-bloat 0.9.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-bloat"]
"cargo-deadlinks 0.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-deadlinks"]
"cargo-deny 0.7.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-deny"]
"cargo-deps 1.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-deps"]
"cargo-expand 0.6.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-expand"]
"cargo-generate 0.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-generate"]
"cargo-make 0.32.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-make", "makers"]
"cargo-sweep 0.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-sweep"]
"cargo-udeps 0.1.12 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-udeps"]
"cargo-watch 7.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-watch"]
"hyperfine 1.10.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hyperfine"]
"mdbook 0.4.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["mdbook"]
"mdbook-linkcheck 0.7.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["mdbook-linkcheck"]
"mdbook-plantuml 0.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["mdbook-plantuml"]
"rust-analyzer 0.1.0 (path+file:///home/veetaha/dev/rust-analyzer/crates/rust-analyzer)" = ["rust-analyzer"]
"sccache 0.2.13 (registry+https://github.com/rust-lang/crates.io-index)" = ["sccache"]
